#!/usr/bin/env python3

HEADER_TEMPLATE = '''/*
* Copyright (c) 2023-2024, NVIDIA CORPORATION.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*
* NOTE: this file is generated by search_00_generate.py
*
* Make changes there and run in this directory:
*
* > python search_00_generate.py
*
*/

#include <cuvs/neighbors/vecflow.hpp>
#include "../vecflow_search.cuh"

#define instantiate_search_vecflow_d(data_t) \\
 void cuvs::neighbors::vecflow::search( \\
	 cuvs::neighbors::vecflow::index<data_t, int64_t>& idx, \\
	 raft::device_matrix_view<const data_t, int64_t> queries, \\
	 raft::device_vector_view<uint32_t, int64_t> query_labels, \\
	 int itopk_size, \\
	 raft::device_matrix_view<uint32_t, int64_t> neighbors, \\
	 raft::device_matrix_view<float, int64_t> distances) \\
 {{ \\
	 search_vecflow_index_impl<{0}>( \\
		 idx, queries, query_labels, itopk_size, neighbors, distances); \\
 }}

instantiate_search_vecflow_d({0});

#undef instantiate_search_vecflow_d'''

def generate_files():
	file_configs = {
		"search_vecflow_float.cu": "float"
	}
	
	for filename, data_t in file_configs.items():
		content = HEADER_TEMPLATE.format(data_t)
		with open(filename, "w") as f:
			f.write(content)

if __name__ == "__main__":
	generate_files()